# Generated by Django 4.1.7 on 2023-04-18 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
