# Generated by Django 4.1.7 on 2023-03-25 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_deliveryman_status'),
        ('ordering', '0006_alter_order_delivery_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_deliveryman', to='accounts.deliveryman'),
        ),
    ]
