# Generated by Django 4.1.7 on 2023-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0007_order_deliveryman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Доставлено', 'Доставлено'), ('В дорозі', 'В дорозі'), ('Не підтверджено', 'Не підтверджено'), ('Підтверджено', 'Підтверджено'), ('Очікується', 'Очікується'), ('Скасовано', 'Скасовано')], default='', max_length=20),
        ),
    ]
