# Generated by Django 4.1.7 on 2023-03-27 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_arrival',
        ),
    ]
