# Generated by Django 4.1.7 on 2023-03-27 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ordering', '0009_remove_order_date_arrival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_deliveryman', to=settings.AUTH_USER_MODEL),
        ),
    ]
