# Generated by Django 4.1.7 on 2023-04-05 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cartitem', '0008_carts_modified_at'),
        ('ordering', '0010_alter_order_deliveryman'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cartitem.carts'),
        ),
    ]
