# Generated by Django 4.1.7 on 2023-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
