# Generated by Django 4.1.7 on 2023-04-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_remove_order_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('delivered', 'Доставлено'), ('in_transit', 'В дорозі'), ('not_confirmed', 'Не підтверджено'), ('confirmed', 'Підтверджено'), ('is_expected', 'Очікується'), ('canceled', 'Скасовано')], default='', max_length=20),
        ),
    ]
