# Generated by Django 4.1.7 on 2023-04-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
