# Generated by Django 4.1.7 on 2023-04-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_alter_order_delivery_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
