# Generated by Django 4.1.7 on 2023-04-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0015_order_driver_latitude_order_driver_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
