# Generated by Django 4.1.7 on 2023-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0012_alter_customuser_groups_delete_customgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='name')),
                ('permissions', models.ManyToManyField(blank=True, help_text='The permissions this group has. A group will get all permissions granted to each of its members.', related_name='custom_groups', to='auth.permission', verbose_name='permissions')),
            ],
            options={
                'verbose_name': 'Custom Groups',
                'verbose_name_plural': 'groups',
            },
        ),
    ]
