# Generated by Django 4.1.7 on 2023-03-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='military',
            name='military_rank',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
