# Generated by Django 4.1.7 on 2023-03-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_deliveryman_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryman',
            name='status',
            field=models.CharField(choices=[('В дорозі', 'В дорозі'), ('Вільний', 'Вільний'), ('Недоступний', 'Недоступний')], default='Недоступний', max_length=20),
        ),
    ]
