# Generated by Django 4.1.7 on 2023-04-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_deliveryman_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Учасник', 'verbose_name_plural': 'Всі Учасники'},
        ),
        migrations.AlterModelOptions(
            name='deliveryman',
            options={'verbose_name': 'Доставщик', 'verbose_name_plural': 'Доставщики'},
        ),
        migrations.AlterModelOptions(
            name='military',
            options={'verbose_name': 'Військовий', 'verbose_name_plural': 'Військові'},
        ),
        migrations.AlterModelOptions(
            name='volunteer',
            options={'verbose_name': 'Волонтер', 'verbose_name_plural': 'Волонтери'},
        ),
        migrations.AlterField(
            model_name='deliveryman',
            name='status',
            field=models.CharField(choices=[('В дорозі', 'В дорозі'), ('Вільний', 'Вільний'), ('Недоступний', 'Недоступний')], default='Вільний', max_length=20),
        ),
    ]
