# Generated by Django 4.1.7 on 2023-04-05 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartitem', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
