# Generated by Django 4.1.7 on 2023-04-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_remove_order_cart'),
        ('cartitem', '0008_carts_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='items',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='user',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Carts',
        ),
    ]
